# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171105_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='观看数'),
        ),
    ]
