# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_click_nums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='edit_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
